apiVersion: apps/v1
kind: Deployment
metadata:
  name: yaki-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yaki-app
  template:
    metadata:
      labels:
        app: yaki-app
    spec:
      containers:
      - name: web
        image: yaki2026/yaki-app:v1 # <--- ודא שדחפת את האימג' הזה ל-Docker Hub
        imagePullPolicy: Always # נשנה ל-Always כדי שימשוך מהענן
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: yaki-service
spec:
  selector:
    app: yaki-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30500 # תוכל לגשת בכתובת http://10.226.188.153:30500
  type: NodePort
